services:
  # Nest.js application
  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: postgres_db
    ports:
      - "3000:3000"
    networks:
      - nestjs_cms

  # PostgreSQL database
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_cms

networks:
  nestjs_cms:
    driver: bridge

# Volumes for persistent data
volumes:
  postgres_data:
